### ISSUE TITLE
`.json()` cannot put/get `NaN` correctly.

### ISSUE THREAD

**Issue by dinfer** [mixer/etcd3#19]
When using '.json()', `NaN` is parsed as `null`.

my wrapper

```typescript
import { Etcd3 } from 'etcd3'
import { posix as path } from 'path'
export class EtcdClient<T> {
    client: Etcd3
    static QUEUE_PREFIX = 'queue'
    constructor(protected rootPath: string = '/') {
        this.client = new Etcd3({
            hosts: [ '127.0.0.1:2379' ]
        })
        if (!path.isAbsolute(this.rootPath)) {
            throw new Error(`the rootPath must be a absolute posix path. but got ${this.rootPath}`)
        }
    }
    protected finalKey(key: string, postfix: string = '') {
        return path.join(this.rootPath, key, postfix)
    }
    async get(key: string): Promise<object|null> {
        return await this.client
            .get(this.finalKey(key))
            .json()
    }
    async put(key: string, value: T) {
        return await this.client
            .put(this.finalKey(key))
            .value(JSON.stringify(value))
            .exec()
    }
    async destroy() {
        this.client.close()
    }
}
```

the test code

```typescript
import { expect } from 'chai'
import { EtcdClient } from './EtcdClient'

describe.only('', () => {
    describe('function', () => {
        const key = '__test_key'
        const body = {
            a: null, 
            b: NaN, 
            c: 1,
            d: true,
            e: 'string', 
            f: [], 
            g: {},
            h: [1, 2, 3],
            i: [null, null],
            j: [undefined, undefined],
            k: [1, 2],
            l: [NaN, NaN],
            m: [999999999999999999999999999999999999999, 999999999999999999999999999999999999999],
            n: [true, false],
            o: ['', ''],
            p: ['stringA', 'stringB'],
            q: [[], [1]],
        }
        let client: EtcdClient<typeof body>
        beforeEach(async () => {
            client = new EtcdClient<typeof body>('/test')
        })
        afterEach(async () => {
            await client.destroy()
        })
        it('get & set', async () => {
            await client.put(key, body)
            const resp = await client.get(key)
            expect(resp).to.eql(body)
        })
    })
})
```

the output

```
 1) function get & set:

     AssertionError: expected { Object (a, b, ...) } to deeply equal { Object (a, b, ...) }
     + expected - actual

      {
        "a": [null]
     -  "b": [null]
     +  "b": NaN
        "c": 1
        "d": true
        "e": "string"
        "f": []
          [null]
          [null]
        ]
        "j": [
     -    [null]
     -    [null]
     +    [undefined]
     +    [undefined]
        ]
        "k": [
          1
          2
        ]
        "l": [
     -    [null]
     -    [null]
     +    NaN
     +    NaN
        ]
        "m": [
          1e+39
          1e+39

     at Object.<anonymous> (src\crawler\storage\EtcdClient.test.ts:47:29)
     at Generator.next (<anonymous>)
     at fulfilled (src\crawler\storage\EtcdClient.test.ts:4:58)
     at <anonymous>
```

**Comment by connor4312** [comment]
Thanks for opening an issue!

This is expected behavior, as JSON has no representation of `NaN`.

```js
$ node
> JSON.stringify({ a: NaN });
'{"a":null}'
```

If storing the validity of a number and distinguishing between null is important, I would recommend something like `{ a: { isNumber: true, value: 42 } }`, which can alternately be `{ a: null }` or `{ a: { isNumber: false, value: NaN } }`.

Let me know if you have any other questions.

**Comment by dinfer** [comment]
thanks for your reply. : )
